"""Compile the canonical RIDE ODD into the committed Relax NG schema.

The script runs the two official TEI Stylesheets transformations directly
through Saxon. The caller supplies a checkout of TEIC/Stylesheets 7.60.0,
whose bundled P5 subset is version 4.11.0a. ``useFixedDate`` removes the
generation timestamp so repeated runs are byte-identical. CI uses ``--check``
to detect drift between ``schema/ride.odd`` and ``schema/ride.rng``. See
``knowledge/pipeline.md`` for the schema maintenance contract.

Usage::

    python scripts/compile_schema.py --stylesheets ../Stylesheets
    python scripts/compile_schema.py --stylesheets ../Stylesheets --check
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ODD = REPO_ROOT / "schema" / "ride.odd"
DEFAULT_OUTPUT = REPO_ROOT / "schema" / "ride.rng"
SUPPORTED_STYLESHEETS_VERSION = "7.60.0"


def _require_file(path: Path, description: str) -> Path:
    if not path.is_file():
        raise FileNotFoundError(f"{description} not found: {path}")
    return path.resolve()


def _check_stylesheets_version(stylesheets: Path) -> None:
    version_path = _require_file(stylesheets / "VERSION", "TEI Stylesheets VERSION")
    version = version_path.read_text(encoding="utf-8").strip()
    if version != SUPPORTED_STYLESHEETS_VERSION:
        raise ValueError(
            "Unsupported TEI Stylesheets version "
            f"{version!r}; expected {SUPPORTED_STYLESHEETS_VERSION}."
        )


def _run_saxon(
    *,
    java: str,
    jar: Path,
    source: Path,
    stylesheet: Path,
    output: Path,
    parameters: dict[str, str],
) -> None:
    command = [
        java,
        "-jar",
        str(jar),
        f"-s:{source}",
        f"-xsl:{stylesheet}",
        f"-o:{output}",
        *(f"{key}={value}" for key, value in parameters.items()),
    ]
    subprocess.run(command, check=True)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _normalize_generated_rng(path: Path) -> None:
    """Use LF endings and remove generator-only trailing horizontal space."""
    content = path.read_bytes()
    has_final_newline = content.endswith((b"\n", b"\r"))
    normalized = b"\n".join(line.rstrip(b" \t") for line in content.splitlines())
    if has_final_newline:
        normalized += b"\n"
    path.write_bytes(normalized)


def compile_schema(
    *,
    stylesheets: Path,
    odd: Path = DEFAULT_ODD,
    output: Path = DEFAULT_OUTPUT,
    java: str = "java",
    check: bool = False,
) -> bool:
    """Compile ``odd`` and return whether it matches the target schema.

    Normal mode replaces ``output`` atomically. Check mode leaves the
    repository untouched and returns ``False`` when the generated bytes differ.
    """
    stylesheets = stylesheets.resolve()
    _check_stylesheets_version(stylesheets)
    odd = _require_file(odd, "RIDE ODD")
    jar = _require_file(stylesheets / "lib" / "saxon10he.jar", "Saxon HE")
    odd_to_odd = _require_file(stylesheets / "odds" / "odd2odd.xsl", "ODD expansion stylesheet")
    odd_to_rng = _require_file(
        stylesheets / "profiles" / "default" / "rng" / "to.xsl",
        "Relax NG stylesheet",
    )
    p5_subset = _require_file(stylesheets / "source" / "p5subset.xml", "TEI P5 subset")

    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="ride-schema-") as temp_dir:
        temp_root = Path(temp_dir)
        processed_odd = temp_root / "ride.processed.odd"
        generated_rng = temp_root / "ride.rng"
        fixed_parameters = {"verbose": "false", "useFixedDate": "true"}

        _run_saxon(
            java=java,
            jar=jar,
            source=odd,
            stylesheet=odd_to_odd,
            output=processed_odd,
            parameters={
                **fixed_parameters,
                "defaultSource": str(p5_subset),
                "selectedSchema": "tei_ride",
                "currentDirectory": str(odd.parent),
            },
        )
        _run_saxon(
            java=java,
            jar=jar,
            source=processed_odd,
            stylesheet=odd_to_rng,
            output=generated_rng,
            parameters={
                **fixed_parameters,
                "lang": "en",
                "directory": str(output.parent),
            },
        )
        _normalize_generated_rng(generated_rng)

        if check:
            _require_file(output, "Committed Relax NG schema")
            return generated_rng.read_bytes() == output.read_bytes()

        temporary_output = output.with_suffix(output.suffix + ".tmp")
        try:
            shutil.copyfile(generated_rng, temporary_output)
            temporary_output.replace(output)
        finally:
            temporary_output.unlink(missing_ok=True)
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Compile schema/ride.odd with pinned TEI Stylesheets."
    )
    parser.add_argument(
        "--stylesheets",
        type=Path,
        required=True,
        help="Checkout of TEIC/Stylesheets v7.60.0.",
    )
    parser.add_argument("--odd", type=Path, default=DEFAULT_ODD)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--java", default="java", help="Java executable.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the committed schema differs.",
    )
    args = parser.parse_args(argv)

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")

    try:
        matches = compile_schema(
            stylesheets=args.stylesheets,
            odd=args.odd,
            output=args.output,
            java=args.java,
            check=args.check,
        )
    except (FileNotFoundError, ValueError, subprocess.CalledProcessError) as exc:
        print(f"ERROR: schema compilation failed: {exc}", file=sys.stderr)
        return 2

    if not matches:
        print(
            "ERROR: schema/ride.rng is stale. Regenerate it with scripts/compile_schema.py.",
            file=sys.stderr,
        )
        print(f"  committed: {_sha256(args.output.resolve())}", file=sys.stderr)
        return 1
    action = "matches the ODD" if args.check else "regenerated"
    print(f"OK: {args.output} {action}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
